### ISSUE TITLE
in_array called with string parameter in so_cuws_hide_visibility_css

### ISSUE THREAD

**Issue by mundschenk-at** [senlin/so-clean-up-wp-seo#24] opened 2017-04-02 08:57 UTC
In `CUWS::so_cuws_hide_visibility_css`, there are [several calls to `in_array`](https://github.com/senlin/so-clean-up-wp-seo/blob/89bc60479207e5e79a75aea3f6db089b46aa91ae/includes/class-so-clean-up-wp-seo.php#L168) with `$this->options['hide_admincolumns']` as its second parameter.

`in_array` expects this parameter to be an array, and at least on my install that assumption is not (always?) true. 

Furthermore, the third parameter (strict equality) should generally be set to `true` when calling `in_array`.

**Comment by mundschenk-at** [comment] 2017-04-02 09:04
OK, it's because the last update changed an option name or something, because previously a column was ticked in the hide admin columns setting.

However, not checking actual input and "requiring" that one checkbox has to be ticked without enforcing the choice is a really bad practice and should be fixed in the code. Also, having to tick "Show all columns" when the other possible choices are "Hide column X" is not a great UX.

**Comment by senlin** [comment] 2017-04-02 14:23
Thanks for your feedback.

Do you have any suggestions?

**Comment by mundschenk-at** [comment] 2017-04-02 14:51
I'd suggest adding proper sanitization callbacks to all the settings fields. [There already is code to invoke those callsbacks](https://github.com/senlin/so-clean-up-wp-seo/blob/master/includes/class-so-clean-up-wp-seo-settings.php#L317), but currently the `'callback'` index is always undefined.

As for the actual sanitization function, you could look at [the way I do it in Media Credit](https://github.com/mundschenk-at/media-credit/blob/master/admin/class-media-credit-admin.php#L1036).

**Comment by senlin** [comment] 2017-04-03 08:12
Thanks for your input. Your PR will be greatly appreciated.

**Comment by mundschenk-at** [comment] 2017-04-03 10:04
@senlin I'm not sure if I'll have enough time to create a PR in the near future ...

**Comment by senlin** [comment] 2017-04-03 10:16
@mundschenk-at 
No worries, I'm not in a hurry and as long as it is not critical and you're not too bothered by it, I guess it will have to wait until you have time :)

Thanks for bringing it up though, maybe someone else feels the urge to contribute further...

**Comment by afragen** [comment] 2017-04-03 13:48
Is there a PHP error or notice occurring?

Checkboxes and radio buttons have a state where they have a value of '1' when checked and are unset when not checked. The tests in the code are for `! empty()`, which is appropriate.

Is there some issue I'm not seeing?

**Comment by afragen** [comment] 2017-04-03 13:57
I see the issue now. I'll make a PR soon.

**Comment by senlin** [comment] 2017-04-03 13:58
Hi Andy, thanks for joining.

I think something messed up with the latest update.

First I discovered that from my version 2.5.5 to 2.6.0 the admin columns for title meta description and focus keyword were in fact still there and the readability column was added to the yoast plugin.

So instead of going from 4 to 2 admin columns, the yoast plugin went from 4 to 5 columns

In 2.6.0 I had changed checkboxes to radio buttons for the admin_columns and in 2.6.1 I tried to revert that back to checkboxes which for some reason didn't work.

Then I decided to rename the admin_columns option to admincolumns instead and that is probably the major problem now.

In your follow up message I see you have probably already discovered what I just wrote down...

Help would certainly be appreciated!

**Comment by afragen** [comment] 2017-04-03 14:03
Hey Piet!

I'll take a look, possibly later today, depends upon my free time in front of a computer. This should be relatively simple.

Andy

**Comment by senlin** [comment] 2017-04-03 15:22
Thanks in advance Andy!

**Comment by afragen** [comment] 2017-04-04 01:25
A little more involved but I think it'll be worth it longterm.

**Comment by senlin** [comment] 2017-04-04 10:46
It indeed looks a bit more involved... 

One of the issues that @mundschenk-at brought up, the one where it should be possible there is no checkbox selected (for the admincolumns setting). I thought I actually did see it addressed, but that could be in your [other PR](https://github.com/senlin/so-clean-up-wp-seo/pull/27)?

**Comment by mundschenk-at** [comment] 2017-04-04 10:48
It's not at the moment, but the UI improvement could probably be moved to a separate issue. It's a related point, but not the same as this one.

**Comment by senlin** [comment] 2017-04-04 11:01
Found a small issue with the readability column setting. 

Although the column does not show in the Edit Posts/Pages screens (as per the default setting), for some reason the box has not been ticked. Please see attached screenshot.

![so_hide_seo_bloat_settings_ _testbed_ _wordpress](https://cloud.githubusercontent.com/assets/650066/24653604/fd8caac6-1925-11e7-96c2-179a6fb8b955.png)

**Comment by senlin** [comment] 2017-04-04 11:06
I fixed a typo, readibility to readability, in [`includes/class-so-clean-up-wp-seo.php`](https://github.com/senlin/so-clean-up-wp-seo/commit/3ce759fd4ef6faaee2d6c2508bc7f9a0fec97340)

**Comment by senlin** [comment] 2017-04-04 11:25
Cannot replicate the issue above.

@mundschenk-at and @afragen can you please test the plugin in its current state and see whether it holds up upgrading to this version from 2.5.x or 2.6.x? There is still 55.3% of the active users on 2.5.x and 28.5% are running 2.6.x. The rest is on older versions.

**Comment by afragen** [comment] 2017-04-04 13:34
@senlin I added https://github.com/senlin/so-clean-up-wp-seo/blob/master/includes/class-so-clean-up-wp-seo.php#L139 which should take care of old and current users. They will see a default array of settings and need to rest to their preferences. If you consider this a _breaking_ change I would version to 3.0.0.

#25 includes a fix if nothing is checked in Admin Columns it will default to checking hide all columns. https://github.com/senlin/so-clean-up-wp-seo/blob/master/includes/class-so-clean-up-wp-seo-settings.php#L103

**Comment by senlin** [comment] 2017-04-04 13:54
Hi Andy,

Thanks for your explanation. I see the first one now, not sure if this change should be considered _breaking_; do you think it is?

Regarding the fix on [L103](https://github.com/senlin/so-clean-up-wp-seo/blob/master/includes/class-so-clean-up-wp-seo-settings.php#L103) in #25 shouldn't that be the opposite? If not any checkbox has been checked, then it means that the user wants to **show** all columns, not hide them. The checkbox for "show all" can then be removed, so the options can be:

* hide all
* hide seo score
* hide readability
* hide title
* hide metadescription
* hide focus keyword

Isn't that also what @mundschenk-at had in mind at the start of this thread?

**Comment by afragen** [comment] 2017-04-04 13:55
I wasn't paying attention to which of the boxes in admin columns was checked by default. I'll take a look.

**Comment by afragen** [comment] 2017-04-04 14:01
That should be a simple change in https://github.com/senlin/so-clean-up-wp-seo/blob/master/includes/class-so-clean-up-wp-seo-settings.php#L103 to an empty array. I guess I had the logic reversed. I'll have to make another change for this too, but shouldn't be that difficult. Famous last words. 😉

So remove show all columns and allow no selection for show all with no explicit option as this is default.

**Comment by afragen** [comment] 2017-04-04 14:03
I think that anything that changes the users settings or requires them to re-enter is a weak breaking change. No fatale but still requires some intervention over a simple update.

**Comment by senlin** [comment] 2017-04-04 14:05
I just swapped out 'all' for 'none' and then when you don't check any of the boxes and save the settings, it automatically ticks the Show All box.

So this still means that the Show All box needs to be there, not entirely what @mundschenk-at had in mind I think as he mentioned earlier that that is bad UI...

Nopt sure how to solve that and since he doesn't seem to have the intention to submit a PR, I think we shall leave it at that then...

**Comment by afragen** [comment] 2017-04-04 14:31
I think since the concept of the plugin is to hide things we could omit all the _all_ and _none_ boxes and allow for no checked boxes. It may mean moving off radio buttons. If you like this direction I could create a PR for it. Let me know.

**Comment by senlin** [comment] 2017-04-04 19:00
Omitting the all and none boxes is a good idea I think, simple is better after all.

But I tried the PR and that is throwing a whole bunch of errors, all having to do with the settings that had all/none choices...

In a brand new test install I just set up I added the PR to the current 2.6.1 and I got a Fatal Error:

`Fatal error: Uncaught Error: Call to undefined method CUWS::get_settings_as_array() in /home/sandnxfw/public_html/wpdev/wp-content/plugins/so-clean-up-wp-seo/admin/class-so-clean-up-wp-seo-admin-api.php:23 Stack trace: #0 /home/sandnxfw/public_html/wpdev/wp-admin/includes/template.php(1343): CUWS_Admin_API->display_field(Array) #1 /home/sandnxfw/public_html/wpdev/wp-admin/includes/template.php(1302): do_settings_fields('cuws_settings', 'standard') #2 /home/sandnxfw/public_html/wpdev/wp-content/plugins/so-clean-up-wp-seo/includes/class-so-clean-up-wp-seo-settings.php(422): do_settings_sections('cuws_settings') #3 /home/sandnxfw/public_html/wpdev/wp-includes/class-wp-hook.php(298): CUWS_Settings->settings_page('') #4 /home/sandnxfw/public_html/wpdev/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /home/sandnxfw/public_html/wpdev/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/sandnxfw/public_html/wpdev/wp-admin/admin.php(222): do_action('seo_page_cuws_s...') #7 {main} thrown in /home/sandnxfw/public_html/wpdev/wp-content/plugins/so-clean-up-wp-seo/admin/class-so-clean-up-wp-seo-admin-api.php on line 23`

**Comment by afragen** [comment] 2017-04-04 21:34
How did you apply the patch? The `get_settings_as_array()` doesn't exist any more. In the most recent version. Let me test against that update.

**Comment by senlin** [comment] 2017-04-04 22:15
> How did you apply the patch?

I replaced the two files with the two files of the PR. Is there another way?

**Comment by afragen** [comment] 2017-04-04 23:15
I just pushed another commit to the PR that I think should fix this.

**Comment by afragen** [comment] 2017-04-04 23:23
> >How did you apply the patch?

> I replaced the two files with the two files of the PR. Is there another way?

Where do I start. I can use GitHub Updater to switch between branches or rollback to any of the last 3 tags. As this plugin doesn't have the appropriate headers to use GitHub Updater, I have another plugin I use to add plugins to GitHub Updater. Sneaky huh?

**Comment by senlin** [comment] 2017-04-05 09:28
Ah yes, of course! Well I can have a look to integrate that too, not sure if it would really be beneficial to this plugin?

Further to your PR #28 , the settings page now indeed works as it should, but now the settings do not seem to have any effect whatsoever on the different parts of the site. In other words, no matter how the settings are set, they do not have the desired effect on the Yoast backend. 

This problem only manifests itself on the multi-options settings.

I have made a [dev branch 3.0.0](https://github.com/senlin/so-clean-up-wp-seo/tree/3.0.0-dev) where I have added all your commits to and have added you as a collaborator to the repo, as that might be a bit handier.

I will have a look now if I can find the issue with the multi-option settings not having any effect. Could it have to do with the css being loaded before the css of the yoast plugin?

**Comment by afragen** [comment] 2017-04-05 14:19
I have fixed the issue with the multiple options not having effect locally. Now I seem to have an issue with one of the options for a single setting not being saved. Trying to track it down.

**Comment by afragen** [comment] 2017-04-05 14:42
I've updated #28 and made a new PR #29 to `pr/28` branch. My issue with setting not being saved was because I didn't comment out the code to reset settings for versions < 3.0.0

**Comment by afragen** [comment] 2017-04-05 15:03
I have commented out the version check as the logic is flawed and it will not fire as intended. I need to rethink this.

**Comment by senlin** [comment] 2017-04-05 15:18
I don't know anymore, we are now a long way from the original issue that @mundschenk-at reported. 

Maybe it is faster to simply revert to 2.5.5 and start from there?

**Comment by afragen** [comment] 2017-04-05 15:22
I'll do some testing later.

**Comment by afragen** [comment] 2017-04-06 15:56
In my testing, updating from v2.2.0 (which I had on my repo) to 2.6.1 (in wp.org) shows all the in_array errors. Updating from 2.2.0 to current PR, no errors. Updating from 2.6.1 to current PR also no errors.

Seems like it's good for a merge, unless there are other issues.

**Comment by senlin** [comment] 2017-04-06 16:43
There are still 2 PRs that are not merged yet. So which version do you have working, with or without those PRs?

**Comment by afragen** [comment] 2017-04-06 17:35
The PR is the same just to 2 different branches, `master` and `pr/28`.

**Comment by senlin** [comment] 2017-04-06 19:24
okay, merged the PRs and downloaded the master. Then I installed 2.6.0 and updated via WP to 2.6.1. I then took the master copy and dropped all the files in my local plugin. 

I have warnings appearing on:
* Content (Readability) / Keyword (SEO) Score
* Help center

For the Admin columns no boxes are ticked, whereas before dropping the new files there I had them to show the Focus Keyword only.

Then after selecting and saving the settings, everything works again.

So we can do 2 things:

1. fix the warnings that are showing (for people who have wp_debug set to true)
2. ignore the warnings that are showing (after all they already do now too) and release this version.

What do you think is the best thing to do? And if we release now, what version number?

**Comment by afragen** [comment] 2017-04-06 19:58
Using your repo I wiped all the `cuws` data from the database.
I installed 2.5.5 and activated the plugin.
I updated via WP to 2.6.1 from the repo and have all the in_array errors
I updated via GitHub Updater to the `master` branch here.
Plugin remains active and all PHP errors are gone after a page refresh.

This most closely approximates the update experience from within WP.

I didn't save any new settings. This is an image of the settings page. I never selected or saved anything from the settings page.

![screencapture-test-yoast-dev-wp-admin-admin-php-1491508482643](https://cloud.githubusercontent.com/assets/1296790/24773015/57ea5e8e-1ac8-11e7-8771-a15e1310c98e.png)

When we release I think there's enough change and _potential_ for breakage ( PHP warnings ) that 3.0.0 might be a good number. Ultimately, it doesn't matter and it's up to you. 😉

**Comment by afragen** [comment] 2017-04-06 19:59
You will need to update the readme.txt for changes as well as the version number.

**Comment by senlin** [comment] 2017-04-06 22:38
> This is an image of the settings page. I never selected or saved anything from the settings page.

The question really is what it does for the user. Does it indeed hide all the admin columns or does it keep the settings the user already set before the update?

I guess we will never really know and I will add a line to the changelog that users will need to re-save the settings after the update.

Would you mind if I make you "official" contributor to the plugin here and on WP?

**Comment by afragen** [comment] 2017-04-06 23:12
My best guess is that it will create new settings for the user, the default ones, and they will need to re-save personal settings. Another reason to version is at 3.0.0 as it _breaks_ the existing settings.

I wouldn't mind at all if you made me an _official_ contributor. I will still defer to you regarding releases.

**Comment by senlin** [comment] 2017-04-06 23:20
That's how we will do it then, thanks.

And thank you for accepting the _official_ contributor role, welcome! 👍

**Comment by senlin** [comment] 2017-04-07 01:19
@mundschenk-at 
[v3.0.0](https://github.com/senlin/so-clean-up-wp-seo/releases/tag/v3.0.0) fixes the issue you originally reported. Update will be shortly available from the WP.org Repo.

**Closed** 2017-04-07 01:30 UTC
Labels: enhancement, help wanted
