### ISSUE TITLE
[feature request] Hide upsell after product deletion

### ISSUE THREAD

**Issue by remaindeer** [senlin/so-clean-up-wp-seo#83] opened 2020-05-17 12:05 UTC
After I delete a product (using WooCommerce), Yoast spams my Product overview page with an upsell. I saw that [a similar feature request](https://github.com/senlin/so-clean-up-wp-seo/issues/44) was created for posts but I wanted to create a new one since I'm still seeing it.

The css classes of the notification are: `yoast-notification notice notice-warning is-dismissible`

## Screenshots
![yoast](https://user-images.githubusercontent.com/402154/82143829-8f728080-9846-11ea-87e7-9a0649df24e2.png)

**Comment by senlin** [comment] 2020-05-17 19:45
Hi Kagan, thank you, good catch!

I will need to see this in action, because I'm afraid that if I block any of the classes you so kindly added, a lot more will be hidden, also useful notifications :)

You say this also happens on posts?

I will run it on one of my test setups and see what I cn come up with. Once I do, I will share an update here of course.

**Comment by remaindeer** [comment] 2020-05-18 19:05
I'd like to thank you for all the work you've put into this plugin!

I just checked and indeed, the spam does come up when you delete posts too:

![spam](https://user-images.githubusercontent.com/402154/82250204-4fe18c80-994b-11ea-9abc-78967ce8241d.png)

Looking forward to seeing you recreate it!

**Comment by senlin** [comment] 2020-05-20 14:08
@remaindeer 

Hi Kagan, just released the new version that hides the notices you reported. 

Closing this issue now, feel free to re-open if you discover some issue(s) with it.

**Comment by senlin** [comment] 2020-06-12 13:33
A user on the WP.org forums just reported that the ads are showing again.

I suspect that in the new Yoast version, they changed the class (again) or something like that...

Will try to find and release another fix/update.

No availability in the next week(s) so PRs are welcome!

**Comment by senlin** [comment] 2020-08-01 10:37
Cannot reproduce the issue, closing

**Closed by senlin** 2020-08-01 10:37 UTC

**Comment by senlin** [comment] 2020-08-01 12:02
Turned out to be that **taxonomy deletion** also triggers this upsell, so included a rule for that, release 3.14.2
